server:
  port: 8888
  servlet:
    session:
      # session超时时间，单位为秒
      timeout: 3600
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/oldx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: FebsHikariCP
