server:
  port: 8888
  servlet:
    session:
      # session超时时间，单位为秒
      timeout: 3600
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/moli?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: FebsHikariCP
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.security: info
moli:
  showsql: true
  security:
    # 登录路径
    login-url: /login
    # 登出路径
    logout-url: /logout
    # 首页路径
    index-url: /index
    # 免认证静态资源路径
    anon-resources-url: /css/**,/js/**,/fonts/**,/img/**





